language: python

# use pythons
python:
  - "3.6"
  - "3.7"

# link services
services:
  - redis-server
  - elasticsearch

# give elasticsearch some time to startup
before_script:
  - sleep 10

# install dependencies
install:
  - pip install -r travis/requirements.txt

# run tests
script:
  - nosetests -c travis/nose.ini

# submit coveralls
after_success:
  coveralls

notifications:
  email:
    - dmitrybelyakov@gmail.com