#!/usr/bin/env python3
from boiler.cli import cli as kernel

# root project command
cli = kernel.cli

# add orm cli
from boiler.cli import db
cli.add_command(db.cli, name='db')

from shiftcontent.cli import cli as project_cli
cli.add_command(project_cli, name='content')

# and run
cli()

